### PR TITLE
Switched to use Pendulum's C timezone implementation

### LINKED ISSUE #45: Backport datetime.timezone to older Python versions?
Starting in Python 3.7, [`datetime.timezone` objects](https://docs.python.org/3/library/datetime.html#timezone-objects) became accessible through [the C-API](https://docs.python.org/3.7/c-api/datetime.html#c.PyTimeZone_FromOffset).

[ciso8601 v2.0.0](https://github.com/closeio/ciso8601/pull/43) is scheduled to take advantage of this when compiled against Python 3.7+. The performance improvements [are dramatic.](https://github.com/closeio/ciso8601/pull/43#issuecomment-388410482)

ciso8601 should consider creating a C implementation of a tzinfo subclass. This could be a backport of cPython's timezone class, or a new implementation. Having such an implementation would:

* allow Python < 3.7 to experience the same performance gains
* allow ciso8601 to sever its dependency on pytz.

### LINKED ISSUE #101: Build fails with GCC 10.2 and PyPy 7.3.3
I have versions:

```
$ pypy3 --version
Python 3.7.9 (7e6e2bb30ac5fbdbd443619cae28c51d5c162a02, Nov 24 2020, 10:03:59)
[PyPy 7.3.3-beta0 with GCC 10.2.0]

$ gcc --version
gcc (GCC) 10.2.0
```

When I run `CFLAGS="$CFLAGS -fcommon" pypy3 -m pip install git+https://github.com/closeio/ciso8601.git`, I get:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/closeio/ciso8601.git
  Cloning https://github.com/closeio/ciso8601.git to /tmp/pip-req-build-zank7ym7
  Running command git clone -q https://github.com/closeio/ciso8601.git /tmp/pip-req-build-zank7ym7
Building wheels for collected packages: ciso8601
  Building wheel for ciso8601 (setup.py): started
  Building wheel for ciso8601 (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zank7ym7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zank7ym7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-k0gy_icr
       cwd: /tmp/pip-req-build-zank7ym7/
  Complete output (27 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'ciso8601/__init__.py' not found (or not a regular file)
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/ciso8601
  copying ciso8601/__init__.pyi -> build/lib.linux-x86_64-3.7/ciso8601
  copying ciso8601/py.typed -> build/lib.linux-x86_64-3.7/ciso8601
  running build_ext
  building 'ciso8601' extension
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -DNDEBUG -O2 -O2 -march=broadwell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mno-sgx -mbmi2 -mno-pconfig -mno-wbnoinvd -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-mwaitx -mno-clzero -mno-pku -mno-rdpid -mno-gfni -mno-shstk -mno-avx512vbmi2 -mno-avx512vnni -mno-vaes -mno-vpclmulqdq -mno-avx512bitalg -mno-movdiri -mno-movdir64b -mno-waitpkg -mno-cldemote -mno-ptwrite -mtune=broadwell -pipe -fstack-protector-explicit -fno-plt -g -gdwarf -gz -ggdb -Wno-error=deprecated-declarations -fcommon -fPIC -DCISO8601_VERSION=2.1.3 -I/opt/pypy3/include -c module.c -o build/temp.linux-x86_64-3.7/module.o
  module.c: In function ‘_parse’:
  module.c:446:30: warning: implicit declaration of function ‘PyTimeZone_FromOffset’ [-Wimplicit-function-declaration]
    446 |                     tzinfo = PyTimeZone_FromOffset(delta);
        |                              ^~~~~~~~~~~~~~~~~~~~~
  module.c:446:28: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
    446 |                     tzinfo = PyTimeZone_FromOffset(delta);
        |                            ^
  module.c: In function ‘PyInit_ciso8601’:
  module.c:562:11: error: ‘PyDateTime_TimeZone_UTC’ undeclared (first use in this function); did you mean ‘PyDateTime_Time’?
    562 |     utc = PyDateTime_TimeZone_UTC;
        |           ^~~~~~~~~~~~~~~~~~~~~~~
        |           PyDateTime_Time
  module.c:562:11: note: each undeclared identifier is reported only once for each function it appears in
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ciso8601
  Running setup.py clean for ciso8601
Failed to build ciso8601
Installing collected packages: ciso8601
    Running setup.py install for ciso8601: started
    Running setup.py install for ciso8601: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zank7ym7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zank7ym7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bxkrj8i3/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jeff/.local/include/python3.7/ciso8601
         cwd: /tmp/pip-req-build-zank7ym7/
    Complete output (27 lines):
    running install
    running build
    running build_py
    package init file 'ciso8601/__init__.py' not found (or not a regular file)
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/ciso8601
    copying ciso8601/__init__.pyi -> build/lib.linux-x86_64-3.7/ciso8601
    copying ciso8601/py.typed -> build/lib.linux-x86_64-3.7/ciso8601
    running build_ext
    building 'ciso8601' extension
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -DNDEBUG -O2 -O2 -march=broadwell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mno-sgx -mbmi2 -mno-pconfig -mno-wbnoinvd -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-mwaitx -mno-clzero -mno-pku -mno-rdpid -mno-gfni -mno-shstk -mno-avx512vbmi2 -mno-avx512vnni -mno-vaes -mno-vpclmulqdq -mno-avx512bitalg -mno-movdiri -mno-movdir64b -mno-waitpkg -mno-cldemote -mno-ptwrite -mtune=broadwell -pipe -fstack-protector-explicit -fno-plt -g -gdwarf -gz -ggdb -Wno-error=deprecated-declarations -fcommon -fPIC -DCISO8601_VERSION=2.1.3 -I/opt/pypy3/include -c module.c -o build/temp.linux-x86_64-3.7/module.o
    module.c: In function ‘_parse’:
    module.c:446:30: warning: implicit declaration of function ‘PyTimeZone_FromOffset’ [-Wimplicit-function-declaration]
      446 |                     tzinfo = PyTimeZone_FromOffset(delta);
          |                              ^~~~~~~~~~~~~~~~~~~~~
    module.c:446:28: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
      446 |                     tzinfo = PyTimeZone_FromOffset(delta);
          |                            ^
    module.c: In function ‘PyInit_ciso8601’:
    module.c:562:11: error: ‘PyDateTime_TimeZone_UTC’ undeclared (first use in this function); did you mean ‘PyDateTime_Time’?
      562 |     utc = PyDateTime_TimeZone_UTC;
          |           ^~~~~~~~~~~~~~~~~~~~~~~
          |           PyDateTime_Time
    module.c:562:11: note: each undeclared identifier is reported only once for each function it appears in
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zank7ym7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zank7ym7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bxkrj8i3/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jeff/.local/include/python3.7/ciso8601 Check the logs for full command output.
```

Primary issue appears to be missing `PyDateTime_TimeZone_UTC`, which is new in Python 3.7 but this version of PyPy claims to implement Python 3.7.

GCC 10 causes these issues sometimes since it switched to the default of `-fno-common`, but that doesn't seem to matter here since adding `-fcommon` to the CFLAGS doesn't change anything.

### PR DESCRIPTION
**Pull request by movermeyer**
Removes dependency on pytz.

Maintains the same error messages so it's backwards compatible with 2.0.x versions.

Resolves #45 (See that issue for performance discussion), and fixes #101

### CODE REVIEW

**Comment by thomasst** [comment]
@movermeyer Thanks for this! Looks like there are some conflicts now. Is this otherwise ready?

File: timezone.c [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+}
+
+/*
+ * def utcoffset(self, dt):
+ *     return timedelta(seconds=self.offset * 60)
+ */
+static PyObject *
+FixedOffset_utcoffset(FixedOffset *self, PyObject *args)
+{
+    return PyDelta_FromDSU(0, self->offset, 0);
```
Comment (thomasst) [inline timezone.c]: It's a bit confusing that this is in seconds in the C implementation, but in minutes in the Python implementation. This probably deserves a comment somewhere.

File: timezone.c [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+    char result_tzname[7] = {0};
+    char sign = '+';
+    int offset = self->offset;
+
+    if (offset < 0) {
+        sign = '-';
+        offset *= -1;
+    }
+
+    sprintf(result_tzname, "%c%02d:%02d", sign, offset / SECS_PER_HOUR,
```
Comment (thomasst) [inline timezone.c]: 1) `sprintf` is dangerous.
2) From what I'm seeing there is no bounds checking for `offset` within this module, so you could pass a huge offset that would cause a buffer overflow, since `%02d` really just means _at least_ 2 characters.

While you're checking for the offset in `module.c`, I'm still not comfortable with this. We should:

1) Use `snprintf` with size 7, just in case.
2) Do an additional bounds check when initializing.

**Review by thomasst — DISMISSED** [review]

File: timezone.c (hunk 1 above)
Comment (movermeyer) [reply timezone.c:71]: I've added a comment to the `struct`, and fixed the `new_fixed_offset_ex` comment to use seconds instead of minutes, and made the comment in the `tests.py` to be explicit about minutes.

File: timezone.c (hunk 2 above)
Comment (movermeyer) [reply timezone.c]: > 1. Use `snprintf` with size 7, just in case.

Done.

> 2. Do an additional bounds check when initializing.

Even though we don't use/expose `FixedOffset_init`, I've added an additional bounds check to it.
The Python code already does bounds checks before calling `new_fixed_offset`

File: timezone.c [hunk 3]
```diff
@@ -0,0 +1,222 @@
...
+{
+    int ready_result = 0;
+    PyDateTime_IMPORT;
+    FixedOffset_type.tp_new = PyType_GenericNew;
+    FixedOffset_type.tp_base = PyDateTimeAPI->TZInfoType;
+    FixedOffset_type.tp_methods = FixedOffset_methods;
+    FixedOffset_type.tp_members = FixedOffset_members;
+    FixedOffset_type.tp_init = (initproc)FixedOffset_init;
+
+    ready_result = PyType_Ready(&FixedOffset_type);
```
Comment (NickG123) [inline timezone.c:217]: I'm not an expert on python classes in c, but I think this should abort on error

File: timezone.c [hunk 4]
```diff
@@ -0,0 +1,222 @@
...
+    Py_INCREF(&FixedOffset_type);
+    PyModule_AddObject(module, "FixedOffset", (PyObject *)&FixedOffset_type);
```
Comment (NickG123) [inline timezone.c:219]: This returns an error that should be checked

File: module.c [hunk 5]
```diff
@@ -558,28 +549,16 @@ initciso8601(void)
...
 #else
-    pytz = PyImport_ImportModule("pytz");
-    if (pytz == NULL) {
-        PyErr_Clear();
-    }
-    else {
-        fixed_offset = PyObject_GetAttrString(pytz, "FixedOffset");
-        utc = PyObject_GetAttrString(pytz, "UTC");
-    }
+    initialize_timezone_code(module);
```
Comment (NickG123) [inline module.c:557]: I forget how Python 2 works here.  But I think you want to make sure an exception is set and abort here on a failure

File: timezone.c (hunk 3 above)
Comment (movermeyer) [reply timezone.c]: Fixed.

File: timezone.c (hunk 4 above)
Comment (movermeyer) [reply timezone.c]: Fixed.

File: module.c (hunk 5 above)
Comment (movermeyer) [reply module.c]: Thanks! 👍 

`initialize_timezone_code` will set the error indicator. I've moved the Python version check into the check of the `initialize_timezone_code`'s return value, so we abort on failure in Python 2.

File: CHANGELOG.md [hunk 6]
```diff
@@ -21,6 +21,11 @@
 # Unreleased
 
 * Added Python 3.9 support
+* Switched to using a C implementation of `timezone` objects.
+    * Much faster parse times for timestamps with timezone information
+        * ~3x faster on Python 2.7, 25% faster on Python 3.7
```
[the remark this answers is not in the document]
Comment (movermeyer) [reply CHANGELOG.md:26]: I just ran the benchmarking scripts, and the results are similar:

```
| Python version | ciso8601 2.1.3 | This PR  | Relative Speedup |
| -------------- | -------------- | -------- | ---------------- |
| Python 3.9     | 207 nsec       | 185 nsec | 1.12x            |
| Python 3.8     | 228 nsec       | 185 nsec | 1.23x            |
| Python 3.7     | 291 nsec       | 253 nsec | 1.15x            |
| Python 3.6     | 432 nsec       | 245 nsec | 1.76x            |
| Python 3.5     | 374 nsec       | 205 nsec | 1.82x            |
| Python 2.7     | 537 nsec       | 202 nsec | 2.65x            |
```

This wasn't especially rigorous, but the results are dramatic enough that I feel confident in them.

[the remark this answers is not in the document]
Comment (movermeyer) [reply CHANGELOG.md]: Changelog updated with these numbers.

File: module.c [hunk 7]
```diff
@@ -558,28 +549,19 @@ initciso8601(void)
...
-    }
-    else {
-        fixed_offset = PyObject_GetAttrString(pytz, "FixedOffset");
-        utc = PyObject_GetAttrString(pytz, "UTC");
-    }
+        return;
 #endif
+    }
+
+    utc = new_fixed_offset(0);
```
Comment (thomasst) [inline module.c:562]: For Python 3.7+, shouldn't we still use `PyDateTime_TimeZone_UTC`?

File: module.c [hunk 8]
```diff
@@ -427,32 +422,34 @@ _parse(PyObject *self, PyObject *args, int parse_any_tzinfo, int rfc3339_only)
...
-                    tzinfo =
-                        PyObject_CallFunction(fixed_offset, "i", tzminute);
+                    PyErr_Format(PyExc_ValueError,
+                                 "('absolute offset is too large', %d)",
+                                 tzminute);
 #endif
+                    return NULL;
+                }
+                else {
+                    tzinfo = new_fixed_offset(60 * tzminute);
```
Comment (thomasst) [inline module.c:452]: Not a new bug, but technically if we hit the we hit the `unconverted data remains` error below, I believe we should also call `if (tzinfo != Py_None && tzinfo != utc) Py_DECREF(tzinfo);`.

File: module.c [hunk 9]
```diff
@@ -11,12 +12,6 @@
     ((PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION >= 3) || PY_MAJOR_VERSION > 3)
 #define PY_VERSION_AT_LEAST_36 \
     ((PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION >= 6) || PY_MAJOR_VERSION > 3)
-#define PY_VERSION_AT_LEAST_37 \
```
[the remark this answers is not in the document]
Comment (movermeyer) [reply module.c:14]: 👍 Removed.

File: module.c (hunk 8 above)
Comment (movermeyer) [reply module.c:450]: Good spot!

File: module.c (hunk 7 above)
Comment (movermeyer) [reply module.c:562]: What's the concern? (Just curious)

It's been a while since I wrote this code so perhaps I'm forgetting something...
My gut tells me that it is better to return a `FixedOffset` for all calls than having a different type for UTC ???

Comment (thomasst) [reply module.c:562]: Wouldn't you want to use the built-in type when available, rather than a custom class?

Also, parsing UTC is common and it's likely faster to just use `PyDateTime_TimeZone_UTC` rather than `new_fixed_offset(0)`.

Comment (movermeyer) [reply module.c:562]: > and it's likely faster to just use PyDateTime_TimeZone_UTC rather than new_fixed_offset(0)

@thomasst You're right. But with https://github.com/closeio/ciso8601/pull/102 (i.e. caching), the difference is a single object creation once, which is not worth optimizing.

So it just comes down to a decision between:

* Returning the built-in when possible
* Returning `FixedOffset` always

🤷 IMO, it's not a big deal either way. I'll let you have the final say.

Comment (movermeyer) [reply module.c:562]: I think you've won me over. I'll make the change.

Comment (movermeyer) [reply module.c:567]: I've brought back the use of `PyDateTime_TimeZone_UTC` in Python 3.7+ for UTC.

I've also added a bunch of tests to ensure that our `FixedOffset` behaves the same as the built-in `timezone` objects. These tests uncovered discrepancies in (e.g. `tzname` returns different things on different Python versions), and I've corrected these.

Comment (movermeyer) [reply module.c:567]: @thomasst 

[This issue](https://github.com/closeio/ciso8601/issues/101) would be a reason in favour of using our `FixedOffset` instead of the built-in.

Not that we officially support PyPy, but if it's the only thing getting in their way... 🤷 

Thoughts?

Comment (thomasst) [reply module.c:562]: According to https://foss.heptapod.net/pypy/pypy/-/issues/3320 wrapping it with `#if PY_VERSION_HEX < 0x03070000 || (PYPY_VERSION && PYPY_VERSION_NUM < 0x07030600)` should let us use it.

I think it would be more elegant to use the built-in when possible. What do you think?

Comment (movermeyer) [reply module.c:567]: @thomasst Yeah, it looks like they are fixing their issue.

Alright, I've switched it back to return the built-in.

File: module.c [hunk 10]
```diff
@@ -558,28 +551,23 @@ initciso8601(void)
...
-        PyErr_Clear();
-    }
-    else {
-        fixed_offset = PyObject_GetAttrString(pytz, "FixedOffset");
-        utc = PyObject_GetAttrString(pytz, "UTC");
+        return;
+#endif
     }
+
+#if PY_VERSION_AT_LEAST_37
```
Comment (thomasst) [inline module.c:564]: Should we use
```
#if PY_VERSION_HEX < 0x03070000 || (PYPY_VERSION && PYPY_VERSION_NUM < 0x07030600)
    utc = new_fixed_offset(0);
#else
    utc = PyDateTime_TimeZone_UTC;
#endif
```
 to be most compatible?

Comment (movermeyer) [reply module.c]: Make sense. Added as `SUPPORTS_37_TIMEZONE_API`

Comment (movermeyer) [reply module.c]: I tested that the build works with `pypy v7.3.5` using:

```
docker run -it --rm=true -v $(dirname `pwd`):/app pypy bash
cd /app
pypy3 setup.py test
```

It fails some of the tests due to difference in the error message printout, but runs fine.

I have **NOT** tested to make sure that it works on the `py3.7` branch of https://foss.heptapod.net/pypy/pypy (i.e. unreleased `pypy v7.3.6`)

**Review by thomasst — APPROVED** [review]
