### PR TITLE
Fix bug with non-optional time parts

### LINKED ISSUE #5: 20140203T10::27 shouldn't parse seconds
A missing minutes fragment between two time separators should cause it to stop parsing and consider the rest of the string junk, but instead it treats minutes as zero.

Test:

```
ciso8601.parse_datetime('20140203T10::27')
```

Expected:

```
datetime.datetime(2014, 2, 3, 10, 0)
```

Actual:

```
datetime.datetime(2014, 2, 3, 10, 0, 27)
```

### LINKED ISSUE #6: 20140203 04:05:.123456 shouldn't parse fractional seconds
A missing seconds fragment between two time separators should cause it to stop parsing and consider the rest of the string junk, but instead it treats seconds as zero.

Test:

ciso8601.parse_datetime('20140203 04:05:.123456')

Expected:

datetime.datetime(2014, 2, 3, 4, 5)

Actual:

datetime.datetime(2014, 2, 3, 4, 5, 0, 123456)

### PR DESCRIPTION
**Pull request by whit537**
In general time parts are optional, but they shouldn't be if there is a subsequent separator, e.g., `20140302 05::01` is missing the minute part and should fail parsing, returning `None`.

Closes #5 and #6.

### CODE REVIEW

**Comment by whit537** [comment]
@thomasst What behavior do you want for trailing separators? Currently `20140302 05:` parses as `(2014, 3, 2, 5, 0)`. Is that desired, or should we return `None` there as well?

**Comment by anemitz** [comment]
@thomasst bump.

File: module.c [hunk 1]
```diff
@@ -94,8 +95,11 @@ static PyObject* _parse(PyObject* self, PyObject* args, int parse_tzinfo)
         else
             Py_RETURN_NONE;
 
-        if (*c == ':') // Optional separator
+        if (*c == ':') { // Optional separator
+            if (hour == -1)  // But if we have it, hour wasn't optional.
```
Comment (thomasst) [inline module.c]: This is unnecessary since `hour` is always parsed if we reach this block (or else we return none above).

File: module.c [hunk 2]
```diff
@@ -107,8 +111,11 @@ static PyObject* _parse(PyObject* self, PyObject* args, int parse_tzinfo)
         } else if (*c >= '6' && *c <= '9')
             Py_RETURN_NONE;
 
-        if (*c == ':') // Optional separator
+        if (*c == ':') { // Optional separator
+            if (minute == -1)  // But if we have it, minute wasn't optional.
```
Comment (thomasst) [inline module.c]: How about we change the minute-clause above to:
`} else if ((*c >= '6' && *c <= '9') || *c == ':')`

File: module.c [hunk 3]
```diff
@@ -122,6 +129,8 @@ static PyObject* _parse(PyObject* self, PyObject* args, int parse_tzinfo)
 
         if (*c == '.' || *c == ',') // separator
         {
+            if (second == -1)
```
Comment (thomasst) [inline module.c]: How about we change the second-clause above to `} else if ((*c >= '6' && *c <= '9') || *c == ':')`?

File: module.c [hunk 4]
```diff
@@ -141,6 +150,9 @@ static PyObject* _parse(PyObject* self, PyObject* args, int parse_tzinfo)
                 usecond *= 10;
         }
     }
+    if (hour == -1) hour = 0;
```
Comment (thomasst) [inline module.c]: If we do the above changes we won't need this hack anymore.

Comment (whit537) [reply module.c]: Done in 7eb474c19528a433ccbc4a34c56ebcd78d2557c5. I added 45aeded35d37da784ed4c7115d942aa70bf74394 so that 7eb474c19528a433ccbc4a34c56ebcd78d2557c5 makes clear the slight behavior change it introduces: `20140203 04:05:.123` now parses with a 0 for seconds vs. `None` before.

**Comment by whit537** [comment]
Running green ... back over to you @thomasst! :)

**Comment by whit537** [comment]
> slight behavior change

Just kidding! I copied and pasted from https://github.com/closeio/ciso8601/pull/31#discussion_r163104658 without thinking it through. Cleaned up in 3cf75bc15a8fd7ef71142af028942881585df93f. 😊

**Comment by thomasst** [comment]
Thanks!
